// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	common.proto
	server.proto

It has these top-level messages:
	Message
	SignIn
	ChatMsg
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type Message struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// Types that are valid to be assigned to Payload:
	//	*Message_Signin
	//	*Message_Chatmsg
	Payload isMessage_Payload `protobuf_oneof:"payload"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto1.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type isMessage_Payload interface {
	isMessage_Payload()
}

type Message_Signin struct {
	Signin *SignIn `protobuf:"bytes,2,opt,name=signin,oneof"`
}
type Message_Chatmsg struct {
	Chatmsg *ChatMsg `protobuf:"bytes,3,opt,name=chatmsg,oneof"`
}

func (*Message_Signin) isMessage_Payload()  {}
func (*Message_Chatmsg) isMessage_Payload() {}

func (m *Message) GetPayload() isMessage_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Message) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Message) GetSignin() *SignIn {
	if x, ok := m.GetPayload().(*Message_Signin); ok {
		return x.Signin
	}
	return nil
}

func (m *Message) GetChatmsg() *ChatMsg {
	if x, ok := m.GetPayload().(*Message_Chatmsg); ok {
		return x.Chatmsg
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Message) XXX_OneofFuncs() (func(msg proto1.Message, b *proto1.Buffer) error, func(msg proto1.Message, tag, wire int, b *proto1.Buffer) (bool, error), func(msg proto1.Message) (n int), []interface{}) {
	return _Message_OneofMarshaler, _Message_OneofUnmarshaler, _Message_OneofSizer, []interface{}{
		(*Message_Signin)(nil),
		(*Message_Chatmsg)(nil),
	}
}

func _Message_OneofMarshaler(msg proto1.Message, b *proto1.Buffer) error {
	m := msg.(*Message)
	// payload
	switch x := m.Payload.(type) {
	case *Message_Signin:
		b.EncodeVarint(2<<3 | proto1.WireBytes)
		if err := b.EncodeMessage(x.Signin); err != nil {
			return err
		}
	case *Message_Chatmsg:
		b.EncodeVarint(3<<3 | proto1.WireBytes)
		if err := b.EncodeMessage(x.Chatmsg); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Message.Payload has unexpected type %T", x)
	}
	return nil
}

func _Message_OneofUnmarshaler(msg proto1.Message, tag, wire int, b *proto1.Buffer) (bool, error) {
	m := msg.(*Message)
	switch tag {
	case 2: // payload.signin
		if wire != proto1.WireBytes {
			return true, proto1.ErrInternalBadWireType
		}
		msg := new(SignIn)
		err := b.DecodeMessage(msg)
		m.Payload = &Message_Signin{msg}
		return true, err
	case 3: // payload.chatmsg
		if wire != proto1.WireBytes {
			return true, proto1.ErrInternalBadWireType
		}
		msg := new(ChatMsg)
		err := b.DecodeMessage(msg)
		m.Payload = &Message_Chatmsg{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Message_OneofSizer(msg proto1.Message) (n int) {
	m := msg.(*Message)
	// payload
	switch x := m.Payload.(type) {
	case *Message_Signin:
		s := proto1.Size(x.Signin)
		n += proto1.SizeVarint(2<<3 | proto1.WireBytes)
		n += proto1.SizeVarint(uint64(s))
		n += s
	case *Message_Chatmsg:
		s := proto1.Size(x.Chatmsg)
		n += proto1.SizeVarint(3<<3 | proto1.WireBytes)
		n += proto1.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type SignIn struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *SignIn) Reset()                    { *m = SignIn{} }
func (m *SignIn) String() string            { return proto1.CompactTextString(m) }
func (*SignIn) ProtoMessage()               {}
func (*SignIn) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SignIn) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ChatMsg struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
}

func (m *ChatMsg) Reset()                    { *m = ChatMsg{} }
func (m *ChatMsg) String() string            { return proto1.CompactTextString(m) }
func (*ChatMsg) ProtoMessage()               {}
func (*ChatMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ChatMsg) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ChatMsg) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto1.RegisterType((*Message)(nil), "proto.Message")
	proto1.RegisterType((*SignIn)(nil), "proto.SignIn")
	proto1.RegisterType((*ChatMsg)(nil), "proto.ChatMsg")
}

func init() { proto1.RegisterFile("common.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 174 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xce, 0xcf, 0xcd,
	0xcd, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0xb5, 0x5c, 0xec,
	0xbe, 0xa9, 0xc5, 0xc5, 0x89, 0xe9, 0xa9, 0x42, 0x42, 0x5c, 0x2c, 0x79, 0x89, 0xb9, 0xa9, 0x12,
	0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x90, 0x3a, 0x17, 0x5b, 0x71, 0x66, 0x7a, 0x5e,
	0x66, 0x9e, 0x04, 0x93, 0x02, 0xa3, 0x06, 0xb7, 0x11, 0x2f, 0x44, 0xb7, 0x5e, 0x70, 0x66, 0x7a,
	0x9e, 0x67, 0x9e, 0x07, 0x43, 0x10, 0x54, 0x5a, 0x48, 0x8b, 0x8b, 0x3d, 0x39, 0x23, 0xb1, 0x24,
	0xb7, 0x38, 0x5d, 0x82, 0x19, 0xac, 0x92, 0x0f, 0xaa, 0xd2, 0x39, 0x23, 0xb1, 0xc4, 0xb7, 0x38,
	0xdd, 0x83, 0x21, 0x08, 0xa6, 0xc0, 0x89, 0x93, 0x8b, 0xbd, 0x20, 0xb1, 0x32, 0x27, 0x3f, 0x31,
	0x45, 0x49, 0x86, 0x8b, 0x0d, 0x62, 0x14, 0x36, 0xdb, 0x95, 0xf4, 0xb9, 0xd8, 0xa1, 0xda, 0xb1,
	0x3a, 0x4e, 0x80, 0x8b, 0x19, 0x64, 0x1f, 0x13, 0x58, 0x08, 0xc4, 0x4c, 0x62, 0x03, 0xdb, 0x69,
	0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xd0, 0x22, 0x51, 0x85, 0xeb, 0x00, 0x00, 0x00,
}
